color: null
fieldLayouts:
  65b2c91d-08a3-4121-bb19-ad251f67a027:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T02:54:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 161945cc-af61-484c-b33f-6c0f7953f68e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T02:54:22+00:00'
            elementCondition: null
            fieldUid: 0439cd5c-c1bb-4cbc-89c3-76b49c2acee5 # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: defdc1a7-3a9c-4725-8a36-57f6585621ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T02:54:22+00:00'
            elementCondition: null
            fieldUid: 82a497c3-e8af-48fa-ba25-5ee67db27f13 # List
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9775004f-243b-4f9e-b442-3030f8efddf1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 02808a2b-0b6b-4345-b409-17d0ccceeb3d
        userCondition: null
handle: counts
hasTitleField: true
icon: ''
name: counts
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
