color: null
fieldLayouts:
  ab4e39df-db2f-402f-a748-705ba214f233:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-07T03:14:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 28ac10ea-d361-4574-b694-b6bc70fd7eb5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T15:06:21+00:00'
            elementCondition: null
            fieldUid: bd2542ae-0e50-4d2a-8e7d-b096b415f38c # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a09fc55d-4e5d-4344-a7ff-e992668a0c99
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T15:06:21+00:00'
            elementCondition: null
            fieldUid: 563e5a1e-b687-4c7d-a592-d6369941d6f9 # Gallery Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3281f29a-803e-446e-9ec0-8d8647dd0b83
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9cd5cf62-ab52-4ee5-b72b-c71ccb243976
        userCondition: null
handle: galery
hasTitleField: true
icon: ''
name: Galery
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
