color: null
fieldLayouts:
  09b699c4-059f-4187-940b-0a81b751a81c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T14:56:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d0caf5cf-6609-4f9c-989f-d7aad977a738
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T15:03:00+00:00'
            elementCondition: null
            fieldUid: e583f145-00c3-4eab-aeac-a445f67f361f # Paragraf
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5728c44-5465-4183-bc5e-e13841374459
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T15:03:00+00:00'
            elementCondition: null
            fieldUid: bd2542ae-0e50-4d2a-8e7d-b096b415f38c # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8bc3a26-d7e0-45e9-afd2-9511376a1e78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T15:03:00+00:00'
            elementCondition: null
            fieldUid: 991db876-bf53-4186-b54c-67229d91b09f # Button Text 
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80672ba2-0530-4fa8-8bd8-5d98a8867152
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T15:03:00+00:00'
            elementCondition: null
            fieldUid: db57af9c-9cae-43f8-8d91-4c87f55b948f # Button Link 
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 438bfff5-c2eb-4aa3-8be4-f20464cf3441
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 86ea2658-9770-4145-a30e-08d7a7c73527
        userCondition: null
handle: hero
hasTitleField: true
icon: ''
name: Hero
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
