color: null
fieldLayouts:
  27a523d9-0674-4a06-8624-404174b2b15c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T07:27:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6994a901-9f91-4bf5-bbdc-d21e3299ecd5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T13:44:22+00:00'
            elementCondition: null
            fieldUid: 0439cd5c-c1bb-4cbc-89c3-76b49c2acee5 # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f42320a-ade0-4dee-8d2c-13fa0d091291
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 005e5be0-7ec2-4f23-81cc-e148dabf5395
        userCondition: null
handle: homePage
hasTitleField: true
icon: ''
name: 'Home Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
