color: null
fieldLayouts:
  27a523d9-0674-4a06-8624-404174b2b15c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T07:27:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6994a901-9f91-4bf5-bbdc-d21e3299ecd5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-13T08:28:37+00:00'
            elementCondition: null
            fieldUid: 38fe6ea5-fa58-4b31-80f2-dbfa5c544461 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caa6c527-ef4b-429c-ab28-3c66d0eb9fd7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 005e5be0-7ec2-4f23-81cc-e148dabf5395
        userCondition: null
handle: homePage
hasTitleField: true
icon: ''
name: 'Home Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
