color: null
fieldLayouts:
  23cfa3d0-d68b-47b8-b8ab-00f85180a01a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T06:46:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: afde9186-a379-4b69-8a4e-2b9edbe89851
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T06:46:12+00:00'
            elementCondition: null
            fieldUid: b4b37b1a-58a0-407c-9407-6900b3eac796 # List People
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc888c70-9817-448f-9679-211b5bf83da1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1260da80-8cf1-42b6-8684-148f6ab8042b
        userCondition: null
handle: people
hasTitleField: true
icon: ''
name: People
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
