color: null
fieldLayouts:
  af9b2d17-b972-4144-8beb-55ff35ad518a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T13:59:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: de9c299e-067c-4a41-a6ab-de99e9344e88
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T07:19:55+00:00'
            elementCondition: null
            fieldUid: 3fcf33b8-7bad-4794-8a1f-591cc0cf2ec6 # Post Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16cc027c-4abc-4ad9-ae03-5c20703e1080
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T06:44:23+00:00'
            elementCondition: null
            fieldUid: 82a497c3-e8af-48fa-ba25-5ee67db27f13 # List
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9373a7a9-badd-4f40-96c6-ccfa11028768
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T06:44:23+00:00'
            elementCondition: null
            fieldUid: fd74f978-7cb4-44c8-bd8e-1057e727f173 # Detail
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aea47bf2-9dd5-488c-af3e-d256ed380fab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fe34c042-af62-4dfe-b7fb-32631e5fa2cb
        userCondition: null
handle: post
hasTitleField: true
icon: ''
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
