defaultPlacement: end
fieldLayouts:
  ac0ed34e-caad-4219-9213-5f4e1c6d2759:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T06:45:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 12305290-a105-4a5d-b04f-e5d43558eb3d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T07:08:29+00:00'
            elementCondition: null
            fieldUid: fd74f978-7cb4-44c8-bd8e-1057e727f173 # Detail
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e585e26f-8d53-4b27-953b-e887f14c8719
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6dbfe4c5-aec4-4339-8c30-df425857cadf
        userCondition: null
handle: postCategory
name: 'Post Category'
siteSettings:
  526c3660-3a2f-4270-9389-f02a62b06a11: # Admin Panel
    hasUrls: true
    template: post-category/_category.twig
    uriFormat: 'post-category/{slug}'
structure:
  maxLevels: null
  uid: 2c6625ad-5a0c-4b5d-8752-a7d65f9e6d56
