altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  36537799-1412-4f04-add5-ebcda61e9141:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T01:34:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5c732d96-cd2b-464c-9123-d57137fd6807
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7ce179d4-2c04-4e03-b684-e145c3686f1d
        userCondition: null
fs: featuredImage
handle: featuredImage
name: 'Featured Image'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: featuredImage
transformSubpath: ''
