defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4f5c8269-6fe0-4dad-a3c9-2534c9454f3d # Page
handle: page
maxAuthors: 1
name: Page
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  526c3660-3a2f-4270-9389-f02a62b06a11: # Admin Panel
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: 'page/{slug}'
type: channel
