defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5540424e-b105-48ba-b95e-cb3d5bd000cd # People
handle: people
maxAuthors: 1
name: People
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  526c3660-3a2f-4270-9389-f02a62b06a11: # Admin Panel
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: 'people/{slug}'
type: channel
